#+INCLUDE: ../../../src/setup.org
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../../../src/style.css" />
#+HTML_HEAD: <script type="text/javascript" src="../../../src/script.js"></script>
#+HTML_MATHJAX: align: left indent: 5em tagside: left
#+OPTIONS: tex:t

#+STARTUP: show3levels
#+DATE: <2024-08-26 Mon>
#+PROPERTY: https://englishsummary.com/lesson/lines-written-in-the-early-spring-poem-summary-explanation-in-english-class-11-2/

#+HTML_LINK_UP: https://englishsummary.com/course/direct-and-indirect-speech-rules-with-examples/
#+HTML_LINK_HOME: ../../../index.html


* English Notes
** Adventures in a Banyan Tree
*** Introduction

The story “Adventures in a Banyan tree” written by Ruskin Bond, describes the town of Dehra, nestling in a valley at the foot of the Himalayas and the various interesting activities that took place around a Banyan tree. The story is about a young boy being delighted and enjoying nature while sitting in a Banyan tree.

The boy befriends a young grey coloured squirrel,who used to delve into his pockets to find something. Halfway up the tree, the boy had built a small platform on which he would spend his afternoons by reading interesting stories like that of Treasure Island, Huckleberry Finn and the Novels of Edgar Rice Burroughs and Louisa May Alcott.

Sometimes when he did not wish to read them he would look down through the Banyan leaves at the world below at Grandmother taking down the washing,at the cook arguing with a fruit vendor or at Grandfather complaining at the Hardy Indian marigolds.

*** A Mongoose and a Cobra fight.

It was an April afternoon and the boy was feeling drowsy and was thinking of going for a swim in the pond behind the house. Soon he witnessed a black cobra coming out of a group of cactus. At the same time,a mongoose also came out and went towards the cobra. The Cobra knew that the 3 feet long mongoose was a fine fighter, sharp and furious. But the cobra was also an experienced fighter. He could move with great speed and strike the mongoose. His sharp teeth were full of venom.

It was a battle of champions. The Cobra’s tongue dashed in and out. It raised its body three feet high and raised its broad, spectacled hood. The mongoose’s hair on the spine stood up like bristles, which would help him to prevent his body from getting bitten. While he was witnessing the incident in the Banyan tree, two other spectators, a myna and a jungle crow arrived. They settled down on the cactus to watch the fight.

The cobra swayed slowly from side to side trying to make the mongoose make a false move. But the mongoose knew the power of the glassy eyes of the snake and did not look at them and was looking at a point just below the cobra’s hood. The mongoose neatly jumped to one side and bit the snake on the back and moved away from the reach of the snake. The moment the cobra struck, the crow and the myna flew fast towards it but they collided in mid-air, and making angry noises, they returned to the cactus.

In the final round, the crow and the myna dived at the cobra,where the cobra struck the crow with great force and it died soon, a little away from the cobra. The cobra was weakening. The mongoose raised himself on his back legs and picked the cobra by its nose. The cobra tried hard to escape but soon it stopped fighting. The mongoose then dragged it, catching it by the hood, into the bushes.

*** The rat and the squirrel

The boy then got down from the tree and went to his house. He was happy that the mongoose had won. He encouraged the mongoose to live in the garden to keep the snakes off and often gave it food.

The banyan tree was also the setting for the Strange Case of the Grey Squirrel and the White Rat. The Grandfather had bought the white rat from the bazaar for four annas. The boy would often take it to the roots and branches of the old tree. The squirrel and the white rat would together go for outing among the branches.

Then the squirrel Started building a nest. First it tried to build the nest in the boy’s pockets. When he went home, he found straw and grass falling out. One day his Grandmother’s knitting was lost. The next day he saw something glowing in the banyan tree, then he realized it was the end of the steel knitting needle of Grandmother. The hole was filled with knitting. Among the wool there were three white baby squirrels.

Grandfather had never seen white baby squirrels. When he stated that the white rat often visited the tree, his grandfather told him that the rat must be the father of the white baby squirrels. He said that rats and squirrels were related to each other and it was possible for them to have offspring.

** The Snake and the Mirror

*** Introduction

“The snake and the mirror”written by Vaikom Muhammad Basheer , revolves around a horrific incident happened with a bachelor doctor who encountered a snake while admiring himself into the mirror. The story is narrated by the doctor himself in which he seems taking the situation humorously despite the danger.

It was a hot summer night about ten o’clock when the doctor had his meal at the restaurant and he returned to his room.He had just set up medical practice and his earnings were too small .He had about sixty rupees in his suitcase along with some other shirts, dhotis and one solitary black coat.

He then describes his room which had two windows.It was an outer room with one wall facing the open yard and had a tiled roof with long supporting gables that rested on the beam over the wall. The room had no ceiling and there was a regular traffic of rats.

The doctor got up and went out to the veranda for little fresh air but due to the absence of the wind ,he went back into his room and sat down on the chair to read a book “The Materia Medica”. He opend it at the table on which stood a lamp, a mirror,and a small comb lying beside it.
*** Mirror temptation


Being tempted by the mirror kept infront of him he began gazing himself into it as he was a great admirer of beauty and he believed in making himself look handsome. He was unmarried so he realised that he should do something to make his presence felt. He picked up the comb and ran it through his hair and adjusted the parting so that it looked staight and neat. While grooming himself,he could hear some sound but he ignored it.

After admiring himself,he decided that he would shave everyday and would grow a thin moustache to look more handsome after all he was a bachelor and a doctor. He then decided that he would keep an attractive smile on his face as well to look more handsome. Then another idea strucked him that was to marry a fat woman doctor with plenty of money and a good medical practice.

*** Encounter with a snake

Suddenly there was a noise of a rubber tube fallen to the ground. No sooner did he turn than a snake wriggled over the back of the chair and landed on his shoulder.

Soon, the snake coiled on his left arm . The snake was merely inches away from his face. As a consequence, the doctor went into a deep shock and almost turned to stone. He did not jump and tremble as there was no time to do such things. At this moment he felt the presence of God and realised that God might had not liked his words. At this realization of his true worth, the snake left the doctor and moved towards the mirror. As such, the doctor silently escaped and his life was saved.

*** Moral

Through this short story, the author intends to make the readers realise that one should not be boastful of himself and arrogant of temporary achievements because these things are futile in nature. It is the moment of fear that a person realises his actual worth and the useless worldly pleasures. In the story, the doctor was boasting himself of his education and good looks but as soon as he encountered the ferocious snake, he realised that how his life could end within minutes.

** Lines Written in the Early Spring

*** Introduction

In the poem *Lines Written in the Early Spring*, William Wordsworth talks about the beauty of nature. He finds joy and pleasure in the scenery and creatures around him. However, such natural joy is nowhere to be found in man. The poet laments this gap that man has created between humanity and nature. This poem is written in *six stanzas* of four lines each. The rhyme scheme of each stanza is *abab*.

*** Stanza 1- 2

#+BEGIN_VERSE
I heard a thousand blended notes,
While in a grove I sate reclined,
In that sweet mood when pleasant thoughts
Bring sad thoughts to the mind.
To her fair works did Nature link
The human soul that through me ran;
And much it grieved my heart to think
What man has made of man.
#+END_VERSE

The poet says that he *heard a thousand blended notes* while he was sitting reclined in a grove. The blended notes here are the songs of various birds and the sounds of natural elements that have combined together into a beautiful melody. The poet was in that *sweet mood when pleasant thoughts bring sad thoughts to the mind.*

Therefore, although the atmosphere was sweet and happy, his happy thoughts led him to contemplative thoughts that make him sad. Nature linked the *human soul* that ran through the poet to her fair works or the beautiful things she had created. It brought much grief to the poet’s heart to think *what man has made of man.*

He was really sad to think about the state that humanity has come to. Humanity, by disconnecting itself from the harmonies and beauties of nature, has brought itself to a state of disorder and chaos.

*** Stanza 3- 4

#+BEGIN_VERSE
Through primrose tufts, in that green bower,
The periwinkle trailed its wreaths;
And ’tis my faith that every flower
Enjoys the air it breathes.
The birds around me hopped and played,
Their thoughts I cannot measure:—
But the least motion which they made
It seemed a thrill of pleasure.
#+END_VERSE

The poet tells us that periwinkle flowers were scattered in circles through bunches of primroses in a pleasant shady place under the trees. He believes that *every flower enjoys the air it breathes.* Therefore, beautiful creations of Nature such as flowers find joy even in the very air they breathe. They are happy to be alive.

The birds around the poet hopped and played. He cannot fully understand their thoughts, but even their smallest movements seemed to contain *a thrill of pleasure*. The birds were enjoying playing about in their natural habitat. The poet provides us with beautiful images of nature in these stanzas.

*** Stanza 5- 6

#+BEGIN_VERSE
The budding twigs spread out their fan,
To catch the breezy air;
And I must think, do all I can,
That there was pleasure there.
If this belief from heaven be sent,
If such be Nature’s holy plan,
Have I not reason to lament
What man has made of man?
#+END_VERSE

The *budding twigs spread* themselves out like fans to catch the *breezy air*. The poet thinks that there *was pleasure there* too. Seeing such natural joy in everything around him, the poet believes that it might be heaven sent. Therefore, if this natural joy is *Nature’s holy plan*, the poet has *reason to lament what man has made of man*.

The poet is sad about the state of humanity because in distancing itself from nature, it has lost the natural joy that is part of Nature’s divine plan. Humanity has brought misery upon itself through its rejection of nature.
Conclusion

The poet shows us the joy and peace that can be found in the beauty of nature. He wishes that humans too, were a part of this natural splendour. But humanity has disconnected itself so much from the natural world that it cannot feel the joy and clarity that nature offers anymore. It is implied that the poet wishes for humans to re-establish and strengthen their bond with nature.

** Project Tiger

*** Introduction

The lesson “Project Tiger” is written by Satyajith Ray, who was an Indian filmmaker, fiction writer, publisher, illustrator, calligrapher, music composer and film critic as well. The lesson describes that how Satyajith wished to make a movie with a trained tiger. Shooting a movie with a tiger was not an easy task for him as he had to deal with a lot of problems in his film “Goopy Gyne Bagha Byne”. To shoot a scene showing the encounter of a tiger with the heroes ,Goopy and Bagha, Satyajith got a trained tiger with its trainer, Mr. Thorat from the Bharat Circus Company.

*** The unsuccessful shoot

They decided to shoot the scene in a bamboo grove in a village called Notun Gram, and Mr. Thorat and his team reached there with two tigers. There they found a suitable bamboo grove to shoot the first meeting between Goopy , Bagha and the tiger. Thorat came to the location with the tiger. There were some 25 people after taking took permission to watch the shooting. When the cover of the cage was removed, people saw two well-fed and strong tigers. Thorat said that he brought two because if one failed, the other could be used for the shot.

They put a tiger-skin collar around the tiger’s neck and tied one end of a thin- but-strong wire to this collar and the other end to an iron rod fixed to the ground. Mr. Thorat opened the cage and called out to the tiger, who ferociously jumped out of the cage and charged at the audience.

The trainer Mr. Thorat could not bring it under his control, but it calmed down after a while. They took the required shots, but later found that the camera had failed to work, and the shots were too dark.

*** The final shoot

They had to reshoot the scenes again in a village called Boral, near Calcutta. The lorry once again came with Thorat, the tiger, the steel wire, the special collar and the rod. The whole village came to see the shooting. The villagers were warned to keep themselves at least 70 feet away from the scene of shooting.

The shooting began and Thorat opened the door of the cage. The tiger came out with a loud roar, and charged straight at the villagers. The crowd, some 150 people, melted away as if by magic. After that the tiger calmed down like an obedient child and walked over to the spot that was chosen, paced about as it was required to do, and then went back to its trainer. Ray and his men took all the required shots. This time the camera also worked well, and all the shots were perfect.

** My Sister’s Shoes

*** Introduction

“My sister’s shoes” is an extract from the screen play of the film”Children of Heaven” directed by Majid Majidi. The story revolves around two little siblings -Ali and Zahra, who belonged to a poor family and couldn’t even tell their parents about the lost shoes because of their family’s financial issues.

All the four scenes in the story depicts the hardships, poverty and the maturity of the children in a difficult time. Ali, presented as the protagonist of the play is hardworking, affectionate and full supportive to his family. One day he took his sister, Zahra’s shoes at a Cobbler’s shop for repairing and then with the repaired shoes he moved towards the bakery. Ali enters a bakery and collects some baked nan, stacks them on a piece of cloth and ties the cloth into a bundle.

*** The misfortune

Ali then visits to buy some potatoes at Akbar’s shop where he was informed and warned that his family’s credit was over the limit. The shop owner,Akbar, informed Ali that they should pay some money otherwise they would not get any more vegetable on credit. Meanwhile a junk collector comes and takes Ali’s bag of shoes thinking that it as junk. Ali comes out and searches his bag. He goes to the pile of boxes in front of the shop and picks the bundle of Nan and then looks for the bag of shoes. The vegetable boxes tumbled and vegetables got scattered on the ground.All these made Akbar extremely furious and he asked Ali to get lost.

*** Ali’s house

Ali’s mother was bed ridden due to a disk fracture and wanted to get recovery from her disk fracture. She asked Ali’s father about undergoing a surgery to which he rejected this idea as they had no money with them to afford any such process.

Ali and Zahra were aware of the poor financial condition of their parents, so they decided not to tell them about the lost shoes of Zahra as it could give them extra burden of buying a new pair of shoes. They were also afraid that if their parents will know about the loss of shoes, they will get punishment.

*** The conversation

While All and Zahra were doing their homeworks, they began their conversation through writing messages in their notebooks and exchanging between them. Zahra asked Ali what she would wear to school to which Ali suggested her to wear her slippers but later on seeing Zahra’s threatening words about informing about the shoes to the father, Ali replied that if she tells, their father will beat both of them. Finally he permitted Zahra to wear his sneakers when he is back from school.

** Blowing in the Wind

*** Introduction

“Blowin’ in the Wind” is a song written by *Bob Dylan* in 1962. It is a protest song that raises rhetorical questions about peace, war, and freedom. Bob Dylan believes that the answers are there, however, no one dares to find them.

It deals with the ill effects of the Civil Rights Movement during the Vietnam War. Dylan was the view that the government focuses on war and ignores the violation of African Americans

*** Stanza 1

#+BEGIN_VERSE
How many roads must a man walk down
Before you call him a man
How many seas must a white dove sail
Before she sleeps in the sand
Yes, 'n' how many times must the cannon balls fly
Before they're forever banned
The answer, my friend, is blowin' in the wind
The answer is blowin' in the wind
#+END_VERSE

In these lines, the poet throws light on the belief system prevailing those days. It was believed that a boy can become a man only after going to war. Showing his disagreement with this belief asks ‘how many roads’ i.e. how many times a person would be required to fight wars so that he may be called a man.

Another interpretation of this stanza can be as follows. The poet wonders how much life experiences a person has to suffer in order to be called a man. In other words, he wants to say that it is too much that society demands from a person.

In the next line, the poet raises another rhetoric question asking *‘how many seas must a white dove sail‘* i.e. how many times the war will be fought before achieving peace. Sleeping in the sand refers to the fact that there is no war.

In these lines, the poet uses the phrase *“sleeps in the sand”* as a reference to the passage in the Bible that describes the incident of Noah’s sending the doves out to find land after the flooding of the earth. He was searching for a place to land and rest.

In the third line. the poet asks how many times the weapons will be used before they might be totally banned. In other words, the poet says that we have fought enough wars and they should be ended now.

The poet says that the answer to all of the questions he raised in the verses above lies in the winds, i.e. the answer does exist that is waiting for someone to grab it. But the problem is that nobody troubles to quest for those answers.

*** Stanza 2

#+BEGIN_VERSE
How many years can a mountain exist
Before it’s washed to the sea?
Yes ‘n’ how many times can some people exist
Before they’re allowed to be free?
Yes ‘n’ how many times must a man turn his head
Pretending he just doesn’t see?
The answer, my friend, is blowing in the wind
The answer is blowing in the wind
#+END_VERSE

In the first couplet, the poet says that ‘how many years can a mountain exist’. Here mountain symbolises the pride and ego of those who desire war. According to the poet, the lust for the war of the strong (as mountains) will not last for long. It will sink into the sea someday.

In the second couplet, there is a direct reference to the discrimination against the African Americans who were treated as second-class citizens in spite of living in *‘free’* country. The poet wonders when these people will be able to live freely and might not just *‘exist’* on the earth.

In the third couplet, the poet wonders how many times the good men will ignore the unjust and discriminatory things that they see around them.

He is waiting for the day when the people will raise their voice against discrimination instead of pretending that there is no inequality. In the last couplet, he repeats that the answer lies before us and waits for someone to grab it.

*** Stanza 3

#+BEGIN_VERSE
Yes, 'n' how many times must a man look up
Before he can see the sky
Yes, 'n' how many ears must one man have
Before he can hear people cry
Yes, 'n' how many deaths will it take till he knows
That too many people have died
Yes, 'n' how many deaths will it take till he knows
That too many people have died
The answer, my friend, is blowin' in the wind
The answer is blowin' in the wind
#+END_VERSE

In the first couplet, *‘sky‘* represents ‘freedom’. According to him, the sky i.e. freedom is hidden before the wars. So he wonders how many times one will have to face the wars in order to gain freedom and liberty. Here the poet refers to the long quest of the people for freedom.

In the second couplet, he wonders how long the government will remain deaf to the sorrows of the commoners. When it will hear the peoples’ plea against war and in favour of peace.

In the third couplet, he wonders when the government will realise that too many people have died because of war and it should be stopped now. It is a plea of the poet for peace. In the ending couplet, he says that the answers lie before us and we should grab it.

* Grammar

** Narration
*** Introduction to Narration

In Today’s world, learning English language is a must. English has become an absolutely necessary mean for communication in professional, educational, cultural and other fields. And to master the language, you have to properly learn the grammars, which is the core of any language. 

Narration is one of the most important topics in English grammar. Narration will surely help you to write and speak in English perfectly. Narration has its own set of rules, definitions, structures, etc. Knowing them will help you to understand Narration clearly. So, follow and learn the rules, definitions and structures of Narration by heart and you can surely ace it. 

Our first step of learning Narration is to know the basics of it. We are going to begin our lesson with the discussion of easy topics about Narration such as –

   - What is Narration? 
   - Types of Narration
   - Examples of Narration

*** Definition of Narration

Narration is the act of narrating the words of the speaker. It’s a form of expression through which the speaker voices their opinions, thoughts etc. So, whenever someone is speaking or telling something, that act of speaking is called narration. We use narration in day to day conversations, in story-telling, in educational writings etc. 

*** Direct and Indirect Narration

Let’s understand with an example –

Sunny said, “I play cricket.”

Here Sonny is the speaker and he is telling or saying something. 

Another example – 

Sunny said that he played cricket.

Both are examples of narration and they are narrating the same speech. But we see some changes in the way of narrating Sunny’s words. The first narration is told in Direct speech and the second one in Indirect speech. 

Narration can be done through two ways – 

    Direct speech
    Indirect speech 

*** What is Direct Speech?

Direct speech is the narration of speech in its true form, in the exact way the speaker has spoken it. In Direct speech, the spoken sentence is put within inverted commas or quotation marks (“…”). 

Examples of Direct speech 

    Rabi told his mother, “Buy me a football.”                                
    Rupa said to her friend, “I bought a doll.” 

*** What is Indirect Speech?

Indirect speech tells us what the speaker has spoken without quoting the actual words of the speaker. In Indirect speech we don’t have to use comma (,) or inverted comma (“…”).  

Examples of Indirect speech 

    Rabi told his mother to buy him a football.
    Rupa said to her friend that she had bought a doll.

*** Examples of Direct and Indirect Speech

Table:\\
#+BEGIN_EXPORT LaTeX

\begin{tabular}{|l|l|}
\hline  % Add this line at the start
 \textbf{Direct Speech}                     & \textbf{Indirect Speech}                   \\ \hline
The old tree said, “Please, give me water.” & The old tree requested to give him water.  \\ \hline
The fairy said, “I can do magic.”           & The fairy said that she could do magic.    \\ \hline
Puja says, “I like reading books.’’         & Puja says that she likes reading books.    \\ \hline
Swami said, “I live at Malgudi.’’           & Swami said that he lived at Malgudi.       \\ \hline
The hunter said, “I hunted a bear.’’        & The hunter said that he had hunted a bear. \\ \hline
\end{tabular}

#+END_EXPORT

#+BEGIN_ORG

| Direct Speech                               | Indirect Speech                            |
|---------------------------------------------+--------------------------------------------|
| The old tree said, “Please, give me water.” | The old tree requested to give him water.  |
| The fairy said, “I can do magic.”           | The fairy said that she could do magic.    |
| Puja says, “I like reading books.’’         | Puja says that she likes reading books.    |
| Swami said, “I live at Malgudi.’’           | Swami said that he lived at Malgudi.       |
| The hunter said, “I hunted a bear.’’        | The hunter said that he had hunted a bear. |

#+END_ORG
